---
title: "02-SummarizedExperiment"
author: "Valentin Marteau"
params:
  data: "../../tables/pp_interactions"
  lib:  "../lib"
  results:  "../../results/produced_data/pp_interactions"
  prefix: "02-"
output:
  html_notebook:
    theme: spacelab
    highlight: textmate
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: true
---

```{r, results = "hide"}
library(tidyverse)
library(SummarizedExperiment)
library(HDF5Array)

dfs <- lapply(list.files(path = params$results, pattern = "*.tsv", full.names = TRUE), read_tsv)

files <- dir(params$results, pattern = "*.tsv")
files <- sub("01-tidy_", "", files)
files <- sub("\\.tsv", "", files)
names(dfs) <- files

dfs$metadata <- dfs$metadata |>
  mutate(Group = factor(Group, levels = c("Newborn", "C_Ulcerosa", "M_Crohn"))) |>
  mutate(Bait = factor(Bait, levels = c("Ctrl", "A8", "A9"))) |>
  mutate(Patient = factor(Patient))
```

```{r}
make_mtx <- function(df) {
mat <- df |>
  select(-c(2:4)) |>
  pivot_longer(-1) |>
  pivot_wider(names_from = 1, values_from = value) |>
  column_to_rownames("name")
mat <- as.matrix(mat)
return(mat)
}
```

```{r}
se <- SummarizedExperiment(
  assays = list(raw = make_mtx(dfs$raw),
                raw_neg_Ctrl = make_mtx(dfs$raw_neg_Ctrl),
                raw_imputed = make_mtx(dfs$raw_imputed)),
  rowData = dfs$rowData,
  colData = dfs$metadata)

metadata(se)$Project_info <- "Proteome Discoverer 2.2 sampled MS data"
metadata(se)$formula <- Abundance ~Bait + Patient + Group

saveHDF5SummarizedExperiment(x = se, dir = file.path(params$results), prefix = params$prefix, replace = TRUE)

#se <- loadHDF5SummarizedExperiment(dir= file.path(params$results), prefix = params$prefix)
```

# Compute ratios against neg Ctrls
```{r}
ratios <- dfs$raw_imputed |>
  group_by(Patient, Group) |>
  mutate(across(where(is.numeric), ~ .x/.x[Bait == "Ctrl"])) |>
  rowwise() |>
  mutate(total = sum(c_across(where(is.numeric)), na.rm = T)) |>
  relocate(total, .after = Bait) |>
  filter(total != 902) |>
  select(-total) |>
  ungroup() |>
  select_if(~sum(!is.na(.)) > 0)

write_tsv(ratios, file.path(params$results, paste0(params$prefix, "abundance_ratios.tsv")))
```

# Usefull stuff when working with a SummarizedExperiment
```{r}
# Get one of the assays by position or name. assay(se) defaults to the first assay
assay(se)
assay(se, 3)
assayNames(se)
assays(se)$raw
assays(se)$raw_imputed

# Access the other slots of SummarizedExperiment
colData(se)
rowData(se)
metadata(se)

# Subset assay by metadata or RowData attributes
se[, se$Group == "Newborn"]
se[rowData(se)$OrganismName_OS == "Homo sapiens", ]
subset(se, select = Group == "Newborn")

# Get assay dimensions
dim(se)

# Get list of gene/protein/metabolite names
dimnames(se)

head(assay(se))
```