---
title: "04-Check_dist"
author: "Valentin Marteau"
params:
  data: "../../tables/P-P-interactions"
  lib:  "../lib"
  results:  "../../results/produced_data/p-p-interactions"
output:
  html_notebook:
    theme: spacelab
    highlight: textmate
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: true
---

```{r, results = "hide"}
# load required packages
library(tidyverse)
library(vsn)
library(ggridges)
library(gridExtra)
library(cowplot)
```

```{r}
ratios <- read_tsv(file = file.path(params$results, "02-abundance_ratios.tsv"))
imputed <- read_tsv(file = file.path(params$results, "01-tidy_raw_imputed.tsv"))

fct_level <- function(df){
  df |>
  mutate(Group = factor(Group, levels = c("Newborn", "C_Ulcerosa", "M_Crohn"))) |>
  mutate(Bait = factor(Bait, levels = c("Ctrl", "A8", "A9"))) |>
  mutate(Patient = factor(Patient)) |>
  select_if(~sum(!is.na(.)) > 0)
}

ratios <- fct_level(ratios)
imputed <- fct_level(imputed)
```

```{r}
# Normalization using vsn
vsn <- imputed |>
  select(-c(2:4)) |>
  pivot_longer(-1) |>
  pivot_wider(names_from = 1, values_from = value) |>
  column_to_rownames("name") |>
  as.matrix() |>
  justvsn() |>
  t() |> as_tibble() |>
  bind_cols(imputed[, 1:4]) |>
  relocate("ID", "Group", "Bait", "Patient")

# meanSdPlot(justvsn(t(vsn[, -c(1:4)])))
```

```{r}
melt_df <- function(dat){
reshape2::melt(dat, id.vars = c("ID", "Group", "Bait", "Patient"),
               variable.name = "protein",
               value.name = "abundance") |>
    mutate_at(vars(abundance), as.numeric)
}  

ridge_line_plt <- function(dat, title){
  ggplot(dat, aes(x = log2(abundance), y = Group, fill = Group)) +
  geom_density_ridges(scale = 4) + 
  scale_y_discrete(expand = c(0, 0)) +     # will generally have to set the `expand` option
  scale_x_continuous(expand = c(0, 0)) +   # for both axes to remove unneeded padding
  coord_cartesian(clip = "off") + # to avoid clipping of the very top of the top ridgeline
  theme_ridges() +
  ggtitle(title)
}

box_plt <- function(dat, title){
ggplot(dat, aes(x = Bait, y = log2(abundance), fill = Group)) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 0.5) +
  stat_boxplot(geom = 'errorbar', position = position_dodge2(width = 0.75, preserve = "single", reverse = TRUE)) +
  geom_boxplot(width = 0.75, outlier.color = NA, position = position_dodge2(width = 0.75, preserve = "single", reverse = TRUE) ) +
  coord_flip() +
  ggtitle(title)
}
```
```{r}
p <- plot_grid(
  imputed |> melt_df() |> ridge_line_plt("raw imputed"),
  ratios |> melt_df() |> ridge_line_plt("ratios"),
  imputed |> melt_df() |> box_plt("raw imputed"),
  ratios |> melt_df() |> box_plt("ratios")
  )

plot_grid(
vsn |> melt_df() |> ridge_line_plt("raw imputed"),
vsn |> melt_df() |> box_plt("raw imputed")
)
```

```{r}
scatter_plt <- function(df, x_string, y_string, title) {
df |>
    select(-c(2:4)) |>
    pivot_longer(-1) |>
    pivot_wider(names_from = 1, values_from = value) |>
    mutate_if(is.numeric, log2) |>
    ggplot(aes_string(x = x_string, y = y_string)) +
    geom_point(size = 0.3) +
    ggtitle(title)
}

plot_grid(
imputed |> scatter_plt("Newborn_A8_1", "Newborn_A8_2", "imputed"),
ratios |> scatter_plt("Newborn_A8_1", "Newborn_A8_2", "ratios"),
vsn |> scatter_plt("Newborn_A8_1", "Newborn_A8_2", "vsn")
)
```